@startuml
[http-core] as core
[android-http-retrofit-rxjava3-impl] as impl1
[coroutine-http] as impl2

note right of core: 网络请求框架-抽象接口
note bottom of impl1: retrofit+rxjava3实现方式
note bottom of impl2: kotlin协程实现方式

core ..> impl1: 实现
core ..> impl2: 实现


@enduml